### ISSUE TITLE
Eventually update build.py to remove xAvgCharWidth workaround once fonttools is fixed

### ISSUE THREAD

**Issue by davelab6** [googlefonts/morisawa-biz-ud-mincho#3]
Once fonttools fixes https://github.com/fonttools/fonttools/issues/2538 then https://github.com/googlefonts/morisawa-biz-ud-mincho/blob/180fac5e407fe3f047c2edbed1cd683bf9eebaca/sources/build.py#L152 can be updated

**Comment by davelab6** [comment]
@aaronbell I suggested Simon could fix this in that FT issue... who else do you think would be good to get this sorted out?

**Comment by aaronbell** [comment]
@davelab6 if you’re OK with just lifting the code that I used (which essentially follows the FB check code), I can probably submit a fix for this?

**Comment by xxdgwxx** [comment]
I imagine that everyone has seen this by now but just in case, FontTools released a fix: https://github.com/fonttools/fonttools/releases/tag/4.33.0
