### ISSUE TITLE
Incorrect full name in Japanese

### ISSUE THREAD

**Issue by akihironagai** [googlefonts/morisawa-biz-ud-mincho#5]
Similar to: https://github.com/googlefonts/morisawa-biz-ud-gothic/issues/4

It needs to be changed from "BIZ UDPMincho" and "BIZ UDMincho" to "BIZ UDP明朝" and "BIZ UD明朝".

This is information of BIZ UDPMincho (incorrect full name).
![明朝](https://user-images.githubusercontent.com/77012577/160230000-5d8dae70-b447-4342-b304-11ac0c202bac.png)

This is information of BIZ UDPGothic (incorrect font family name).
![ゴシック](https://user-images.githubusercontent.com/77012577/160230001-24859b5d-040a-4c03-ad22-7ccc57a5e174.png)

**Comment by aaronbell** [comment]
Thanks. Fixed in the latest PR.
